// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyASs5KK3JAJ5wwincPE3oaWeRYRFeNI2to',
    appId: '1:669739754062:web:22a5d1e37096d57440591f',
    messagingSenderId: '669739754062',
    projectId: 'yestable-107c6',
    authDomain: 'yestable-107c6.firebaseapp.com',
    databaseURL: 'https://yestable-107c6-default-rtdb.firebaseio.com',
    storageBucket: 'yestable-107c6.firebasestorage.app',
    measurementId: 'G-CW3VBYWNLV',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBGWl1tcYJ1zVd7dCZoflTk2S0S2MuaNss',
    appId: '1:669739754062:android:780681de7ad6352f40591f',
    messagingSenderId: '669739754062',
    projectId: 'yestable-107c6',
    databaseURL: 'https://yestable-107c6-default-rtdb.firebaseio.com',
    storageBucket: 'yestable-107c6.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDFASnyNhsHAnEoQvejYBv4THjacRWr1gQ',
    appId: '1:669739754062:ios:e94909e9e72d4e2b40591f',
    messagingSenderId: '669739754062',
    projectId: 'yestable-107c6',
    databaseURL: 'https://yestable-107c6-default-rtdb.firebaseio.com',
    storageBucket: 'yestable-107c6.firebasestorage.app',
    iosBundleId: 'com.sirentheory.yestable',
  );

}